name: PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_target:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate set "debug_enabled"'
        required: false
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Check GITHUB_TOKEN
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          if [ "$GITHUB_TOKEN" == "" ]; then
            echo "GITHUB_TOKEN is not set"
          else
            echo "GITHUB_TOKEN is set"
          fi

      - name: RUNNING WORKFLOW FROM UPSTREAM
        run: echo "this is the workflow from upstream"
      - name: Check value.txt and git log
        run: |
          echo "value=$(cat value.txt)"
          git log --oneline | head -n 3


